{* A show's rolled-up credits for one role: people = list of name/url/episodes/seasons (FisheyeCredits::programRollup()), most episodes first.
   The first `limit` are shown, linked to their contact where there is one (the hover gives episodes and seasons); the rest sit behind an
   "and N more" link that opens them in place. *}
{strip}
{foreach from=$people item=p name=rp}{if $smarty.foreach.rp.iteration <= $limit}{if !$smarty.foreach.rp.first}, {/if}{if $p.url}<a href="{$p.url|escape}"{if $p.episodes} title="{$p.episodes} {if $p.episodes == 1}{tr}episode{/tr}{else}{tr}episodes{/tr}{/if}, {$p.seasons} {if $p.seasons == 1}{tr}season{/tr}{else}{tr}seasons{/tr}{/if}"{/if}>{$p.name|escape}</a>{if $p.roleList} <span class="credit-role text-muted">{tr}as{/tr} {foreach from=$p.roleList item=r name=rl}{if $r.url}<a href="{$r.url|escape}">{$r.name|escape}</a>{else}{$r.name|escape}{/if}{if !$smarty.foreach.rl.last}, {/if}{/foreach}{if $p.rolesMore} +{$p.rolesMore}{/if}</span>{/if}{if $p.functions} <span class="credit-function text-muted">&ndash; {foreach from=$p.functions item=f name=pf}{$f|escape}{if !$smarty.foreach.pf.last}, {/if}{/foreach}{if $p.functionsMore} +{$p.functionsMore}{/if}</span>{/if}{else}<span{if $p.episodes} title="{$p.episodes} {if $p.episodes == 1}{tr}episode{/tr}{else}{tr}episodes{/tr}{/if}, {$p.seasons} {if $p.seasons == 1}{tr}season{/tr}{else}{tr}seasons{/tr}{/if}"{/if}>{$p.name|escape}</span>{if $p.roleList} <span class="credit-role text-muted">{tr}as{/tr} {foreach from=$p.roleList item=r name=rl}{if $r.url}<a href="{$r.url|escape}">{$r.name|escape}</a>{else}{$r.name|escape}{/if}{if !$smarty.foreach.rl.last}, {/if}{/foreach}{if $p.rolesMore} +{$p.rolesMore}{/if}</span>{/if}{if $p.functions} <span class="credit-function text-muted">&ndash; {foreach from=$p.functions item=f name=pf}{$f|escape}{if !$smarty.foreach.pf.last}, {/if}{/foreach}{if $p.functionsMore} +{$p.functionsMore}{/if}</span>{/if}{/if}{/if}{/foreach}
{if $people|@count > $limit}
<span class="credit-more"><span style="margin:0 0.4em;">&nbsp;...</span><a href="#" onclick="this.style.display='none';this.previousElementSibling.style.display='none';this.nextElementSibling.style.display='inline';return false;">{tr}and{/tr} {$people|@count - $limit} {tr}more{/tr}</a><span style="display:none">{foreach from=$people item=p name=rest}{if $smarty.foreach.rest.iteration > $limit}, {if $p.url}<a href="{$p.url|escape}"{if $p.episodes} title="{$p.episodes} {if $p.episodes == 1}{tr}episode{/tr}{else}{tr}episodes{/tr}{/if}, {$p.seasons} {if $p.seasons == 1}{tr}season{/tr}{else}{tr}seasons{/tr}{/if}"{/if}>{$p.name|escape}</a>{if $p.roleList} <span class="credit-role text-muted">{tr}as{/tr} {foreach from=$p.roleList item=r name=rl}{if $r.url}<a href="{$r.url|escape}">{$r.name|escape}</a>{else}{$r.name|escape}{/if}{if !$smarty.foreach.rl.last}, {/if}{/foreach}{if $p.rolesMore} +{$p.rolesMore}{/if}</span>{/if}{if $p.functions} <span class="credit-function text-muted">&ndash; {foreach from=$p.functions item=f name=pf}{$f|escape}{if !$smarty.foreach.pf.last}, {/if}{/foreach}{if $p.functionsMore} +{$p.functionsMore}{/if}</span>{/if}{else}<span{if $p.episodes} title="{$p.episodes} {if $p.episodes == 1}{tr}episode{/tr}{else}{tr}episodes{/tr}{/if}, {$p.seasons} {if $p.seasons == 1}{tr}season{/tr}{else}{tr}seasons{/tr}{/if}"{/if}>{$p.name|escape}</span>{if $p.roleList} <span class="credit-role text-muted">{tr}as{/tr} {foreach from=$p.roleList item=r name=rl}{if $r.url}<a href="{$r.url|escape}">{$r.name|escape}</a>{else}{$r.name|escape}{/if}{if !$smarty.foreach.rl.last}, {/if}{/foreach}{if $p.rolesMore} +{$p.rolesMore}{/if}</span>{/if}{if $p.functions} <span class="credit-function text-muted">&ndash; {foreach from=$p.functions item=f name=pf}{$f|escape}{if !$smarty.foreach.pf.last}, {/if}{/foreach}{if $p.functionsMore} +{$p.functionsMore}{/if}</span>{/if}{/if}{/if}{/foreach}</span></span>
{/if}
{/strip}
